### ISSUE TITLE
Interlock Model Support

### ISSUE THREAD

**Issue by nog3** [HSBNE/hsbneportal#17]
So Interlocks operate a bit differently to doors.

Doors are a one-and-done scenario when it comes to reporting door access, whereas interlocks have three main points of reporting.

1. Session Start
2. Session Heartbeat
3. Session End

It's done this way as interlocks may not always send a session end as a user may turn off the interlock at the wall instead of swiping off. Not ideal or what we expect, but we have to handle it anyway.

Currently interlocks report in at start and end, with the time reported at swipe-off. The below is the ideal flow based on experience with building these thus far, happy to shuffle things around if there's an easier way of doing it.

### Session Start
When a user swipes at an interlock, it checks with the server to see if the card has access to that endpoint over HTTPS.

The server endpoint should respond with a json formatted response in the format as `{"access":1,"uuid":ff88583f-b987-4658-a276-8f2bc38662dc,"timestamp":1532302319}` with access being whether or not the tag ID has access, UUID being a unique session ID and the timestamp being a unix timestamp of when the request was recieved.

Ideally the server would create a database entry recording the endpoint, UUID, time started and a 'time used' of 0 so we can update it with a Session Heartbeat.

The interlock then stores the timestamp (for debugging) and UUID (for reporting).

### Session Heartbeat
Every minute while the interlock is in an active state with access granted it will report in to the server (via HTTPS) that it is still active and how long it has been active for (in milliseconds) as well as the UUID of the session provided in Session Start.

The server should update the usage against the UUID so we can track how much tools are being used and who by and potentially do things like maintenance lockouts in future.

### Session End
When a user turns off an interlock by swiping it reports in over HTTPS to the server with the UUID and how long the tool was on in milliseconds total.

At this point the server should trigger notification to Discord that the tool has been turned off and flag the session as complete.

### Unhandled Edge Cases
There's a few things I don't quite know how to handle from here though and honestly I don't have the chops with Django to pull any of the above off.

The edge cases not currently 100% handled by this are:

1. When someone leaves the tool on and someone turns it off. - This probably need an endpoint or way to signal this to the server so we can identify it.
2. When someone turns the tool of at the wall. - The heartbeats during session are there to capture the usage within a minute or so, but the server will still need to notify to Discord that the session has ended. Maybe a timed callback?

**Comment by jabelone** [comment]
This seems really thought out @nog3 - good work! 

Edge cases:
Number 1 - We can leave the endpoint the same, just specify who turns it on and who turns it off. The portal can check if they match and flag it in the UI/post to discord if they don't.

Number 2 - We can just have a cronjob or something that runs every few minutes and marks tools as off (then pings the user on discord).

**Comment by davidbuzz** [comment]
Just a couple of thoughts to add...
1. The current doors actually do have a 'heartbeat' type message posted regularly , so the GUI can report the online/offline and last-seen timestamp. Seems to me there might be value in handling these kinda the same way.
2. There doesn't seem any need for a "session end" as nog described it, to me it's behaviour is equivalent to the heartbeat , which it could just do again (for the last time) when a user swipes off. The background cronjob that 'marks tools as off when it hasnt seen a heartbeat' can be the only thing doing that.

**Comment by jabelone** [comment]
I think the reason we wanted to have both the session end and the cron job was so we can differentiate between a user swiping off and it timing out. (then ping the user and say you need to swipe off next time) However I kinda agree with buzz that it's not really necessary. You can just stop sending a heartbeat and the cronjob will catch it. Although I suspect it's not really that much more complex to add a session end.

**Comment by jabelone** [comment]
I've just pushed some code for basic interlock support so I'm going to close this for now. :) There is no cronjob as all currently we don't really need it. When (if) we implement notifications of machines being left on etc then we'll need to tweak it a bit and add the cronjob.
