### ISSUE TITLE
Add support for door usage logging

### ISSUE THREAD

**Issue by nog3** [HSBNE/hsbneportal#18]
Both Doors and Interlocks should be touching the server on a 5-10 minute schedule for a few reasons.

1. To let us know when one drops out of service unexpectedly.
2. To check if the server is still up, which determines whether it should use the local cache or if it should talk to the server.
3. To update the local rolling cache of tags (if access has changed recently)

Additionally, it's on my roadmap that doors will report whether they're open or not in this heartbeat message. It'd be super if we can handle logging the state for usage patterns as well as the most recent state for other future features like the 'Last Person Out' page.

I imagine most of this is already done, but it'd be nice to confirm :)

**Comment by jabelone** [comment]
Doors currently update the last_seen field automatically, everytime something queries the API for any door. :) I'll be sure to build that into the interlock code too.

I'll change this to add door usage tracking.
