### ISSUE TITLE
Meeting and Cause Proxies

### ISSUE THREAD

**Issue by nog3** [HSBNE/hsbneportal#19]
One feature I've been asked for a bit is for members to be able to record proxies against meetings online so they don't have to fill out the email proforma.

If members could do this while logged into the portal that would validate their identity and recording it online as well as sending an email to the secretary as per our incorporation rules would be brilliant.

This will likely also require the implementation of a calendar that records meetings and whether they're general or attached to a cause.

I put together a framework of this a while back at https://porthack.hsbne.org/members/proxy/sendproxy.php but well, it does nothing except look nice right now.

**Comment by jabelone** [comment]
this has been mostly done (it's a manual date selection right now) but everything else is fully functional.
