### ISSUE TITLE
cause signup on registration not saved

### ISSUE THREAD

**Issue by InverseInductor** [HSBNE/hsbneportal#23]
Joining one cause at signup does not currently work.
The choice is not reflected in the member profile.
Changing the current causes from the member profile does work.

**Comment by jabelone** [comment]
I can reproduce this too. This is a bizarre bug - I'll have a look.

**Comment by jabelone** [comment]
How are you changing the causes? I made a brand new account and experienced the single cause not saving. However, I clicked on the "Edit Profile" button on the profile page. After selecting one or more cause here it saves correctly.

**Comment by jabelone** [comment]
It was a silly little thing where django wasn't saving the many to many relationships of the causes because the profile hadn't been created yet. I added a call to `profile_form.save_m2m()` under `profile.save()` and it appears to have resolved it.
