### ISSUE TITLE
Member Portal Header Rendering Issue

### ISSUE THREAD

**Issue by nog3** [HSBNE/hsbneportal#25]
This is in Chrome 67.0.3396.99 on windows x64, same in latest Firefox (61.0.1. Fine in Edge.

100% zoom.
![image](https://user-images.githubusercontent.com/1333369/43070165-6f3d9024-8eb2-11e8-893d-030c6d73e9aa.png)

90% zoom.
![image](https://user-images.githubusercontent.com/1333369/43070291-d0a22cf8-8eb2-11e8-8c42-e1da1ce60ee8.png)

**Comment by jabelone** [comment]
That's certainly strange! I don't have a wide variety of screen resolutions and displays to test it on so I'm having trouble reproducing it. I'll play around to see if I can recreate it.

**Comment by jabelone** [comment]
I can't seem to reproduce it on any device I have so I can't really troubleshoot what's going on. My best guess is one of the divs on the right are pushing over to the left for some reason which is hiding the word "Portal".

**Comment by nog3** [comment]
This appears to be a font size issue on the specific machine I was using. Closing.
