### ISSUE TITLE
Add 'Last Seen' for Member Logins in the Portal.

### ISSUE THREAD

**Issue by nog3** [HSBNE/hsbneportal#26]
To track down if people are using the portal or not.

**Comment by ZeroCoolHacker** [comment]
You can use the user_logged_in signal to set the last_seen to timezone.now(). 
I can do it but i am just not sure in which file to put the reciever. 
Putting it in urls would make us know whats happening in the code but the urls file should specifically be used for urls
Putting it in views would in a way hide the reciever from the eyes of the programmer.
whats your take?
