### ISSUE TITLE
Contacts/members do not appear to integrate with xero.

### ISSUE THREAD

**Issue by davidbuzz** [HSBNE/hsbneportal#40]
Contacts/members do not appear to integrate with xero.
Needs this , and more , before it can replace current system.

**Comment by jabelone** [comment]
Ooh thanks for that, I completely forgot!

**Comment by jabelone** [comment]
Done. A new Xero contact will automatically be created when someone clicks the "make member" button or the "resend to xero" button.

**Comment by jabelone** [comment]
Yeah it does and it's stored on the user profile. It also goes through and checks each contact in Xero to make sure there are no duplicate names, emails or account numbers.

**Comment by jabelone** [comment]
It also stores the Xero contact ID for when I implement invoice generation in the near future.
