### ISSUE TITLE
Improve invoicing system

### ISSUE THREAD

**Issue by davidbuzz** [HSBNE/hsbneportal#41]
Does not have Invoice generation, and , does not appear to integrate invoices with xero. 
Needs this , and more , before it can replace current system.

**Comment by jabelone** [comment]
I've implemented this in the latest push. It obviously needs more thorough testing before use, but should be completely working.

There is a daily cronjob that checks if anyone has overdue fees and deactivates their account, or reactivates it if they no longer have overdue fees. There is another one that should be run once a month (on the 15th) that will generate a membership fee invoice for anyone who hasn't had one generated that month. This ensures anyone who has recently signed up won't get double invoiced by the portal.

**Comment by davidbuzz** [comment]
jabelone and i diuscussed this in person, and there are some tweaks to the invoicing that need to be revised, such as:
not everyone is invoiced every month  ( some are quarterly, or even yearly , and woofers are not at all)
system need to record the membership payment level along with last-invoice date and last-payment date in order to determine the subset of user/s to invoice at the start of each month and the amount to invoice them.
at begging of month, invoices need to be pushed into Xero with "draft" status , and email the treasurer the list of invoices, so that treasurer can cross-check invoice amounts, etc, tweak any last-minute changes, and then bulk-approve the invoices in Xero ( this is really easy ) .

**Comment by davidbuzz** [comment]
... oh, and the push-invoice-to-xero endpoint  that's currently written in php could be used as-is, as it just expects a GET request, and returns JSON, but jabelone suggested he would probably rewrite it in the Xero python API as he's already comfortable with it.
