### ISSUE TITLE
Add: Fetch Webcam Images every 5 Minutes

### ISSUE THREAD

**Issue by nog3** [HSBNE/hsbneportal#46]
Right now this is done via a cron job on the old server which uses the Unifi NVR Api to pull a snapshot from the relevant camera.

We can probably just continue doing this, after migrating the cron job. Right now the webcams point at the pre-hosted image on porthack though.

**Comment by jabelone** [comment]
This is now done. For future reference, the crontab entries required to make this work are below.

```
*/5 * * * * wget -O /var/www/portal/webcams/greenroom.jpg "https://<NVR_IP>/api/2.0/snapshot/camera/<CAMERA_ID>?force=true&apiKey=<INSERT_KEY>&width=800" >/dev/null 2>&1
*/5 * * * * wget -O /var/www/portal/webcams/quad.jpg "https://<NVR_IP>/api/2.0/snapshot/camera/<CAMERA_ID>?force=true&apiKey=<INSERT_KEY>&width=800" >/dev/null 2>&1

```

Apache config to map the folder publicly:
```
Alias /webcamsnapshots /var/www/portal/webcams
```
