### ISSUE TITLE
Add Asset Register 

### ISSUE THREAD

**Issue by nog3** [HSBNE/hsbneportal#49]
This is planned to expand on report issue form so that we can tie a report issue URL to an asset in the system.

At least should have:
- Asset ID
- Asset Name
- Asset Owner
- Asset URL (likely the Wiki page for the tool or area).

Will also need forms and endpoints to allow for adding, removing and editing assets.

**Comment by jabelone** [comment]
This is no longer needed as we'll be using snipe it.
