### ISSUE TITLE
redirect user to profile page after password change

### ISSUE THREAD

**Issue by jabelone** [HSBNE/hsbneportal#60]
After a password reset is successful, the user should be redirected to the profile page. Because they're not logged in, they will get a login prompt and then django will automatically redirect them to the profile page.

**Comment by dnafication** [comment]
Is there any specific guidelines to contribute to this repo?

**Comment by jabelone** [comment]
Ah yes it is, sorry I forgot to close it. Where did you find this repo, if you don't mind me asking? You're the second "random" person today :)

**Comment by jabelone** [comment]
I've clarified the contributing guidelines a bit so hopefully, it's a bit more clear on how to contribute. At this stage, the project is very specifically designed for HSBNE (Hackerspace Brisbane) so it's probably a bit confusing to help out. Small things like this though are perfect. :)
