### ISSUE TITLE
Add support for Key Tracker

### ISSUE THREAD

**Issue by nog3** [HSBNE/hsbneportal#79]
Previously the Key Tracker would update in MQTT with the current status of the keys and how long they were gone for.

This should probably run on a similar model to interlocks where the portal keeps track of how long the key has been missing for and alert on discord when it reaches important milestones (15 minutes, an hour, a day) etc.

**Comment by roving99** [comment]
I will be in this weekend to check on function of keytracker, to build some new keys (replacements and spares) and to add a fourth key (as mentioned by Alex). Happy to mod the code as suggested.

**Comment by jabelone** [comment]
Basically, the key tracking code will need to regularly check in (a simple HTTP request) with the portal. This should happen about once per minute. Then everytime a key is taken or returned, it should let the portal know via an HTTP request.

Examples of how the endpoints will likely behave:
`portal.hsbne.org/api/keytracker/checkin/`
`portal.hsbne.org/api/key/<int:key_id>/taken/`
`portal.hsbne.org/api/key/<int:key_id>/returned/`
