### ISSUE TITLE
Implement https://spacedirectory.org/

### ISSUE THREAD

**Issue by jabelone** [HSBNE/hsbneportal#8]
Integration into https://spacedirectory.org/ would be great!

At a basic level, a cron job to regenerate the json file and some sensors to help automate that would be really good. Also manual buttons/state control in the portal would be beneficial.

**Comment by jabelone** [comment]
This may be useful: http://spaceapi.net/documentation

**Comment by nog3** [comment]
Right now we have a status.json in the root on the server, I have some hardware put aside for sensor nodes (radiation sensor and weather node) and a lot of the other sensors we can pull from around the place.

I'd say that we need to create the database schema first, create a json endpoint that responds to status.json using the data in that schema and then some api endpoints that take updates and push them to the DB for use in the json endpoint.

**Comment by nog3** [comment]
Basic implementation in 40316b618a7d3e165ac922882ae01cfeba630810 with more to come later.
