### ISSUE TITLE
Feature request: Ability to pull a csv or similiar of members list.

### ISSUE THREAD

**Issue by roving99** [HSBNE/hsbneportal#89]
It would be great to be able to pull a csv/xml/sql of the members list for accounting/analysing. Whatever format requires the least dev time would be fine!
Thanks,
Ian (Roving)

**Comment by roving99** [comment]
Would it be possible to add 'last seen' to this table?

**Comment by lhovo** [comment]
What is the use case for this?
I'm slightly concerned with privacy of personal details.

**Comment by roving99** [comment]
As Treasurer, I would like to be able to analyse membership data. It's all data I can already see, but not easily manipulate -How many members do we have?, how they break down to hacker/starver?, when were they last at the space? etc.

**Comment by jabelone** [comment]
Seems like a decent idea. It will make it a little easier to update our mail chimp list as well.
