### ISSUE TITLE
Proxy Form only renders 3 causes in dropdown.

### ISSUE THREAD

**Issue by nog3** [HSBNE/hsbneportal#91]
This seems to be a bug in how the template is rendering out, since it's rendering out cause in causes.

The actual causes go in order:
Digifab
Blacksmithing
Craftpunk
Electronics
Metalworking
Woodworking
Automotive
Update Me

But the form renders out only
Digifab
Craftpunk
Electronics

This prevents any cause other than those three from submitting proxies via the portal.

**Comment by jabelone** [comment]
The form should only render the causes that you’re part of. Can you please confirm you’re part of those causes?

**Comment by nog3** [comment]
Ah, that makes a bit more sense. Yes, that's the causes I'm in.

**Comment by jabelone** [comment]
No worries 🙂
